//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_BIENPATRIMONIO
    {
        public int IdBienPatrimonio { get; set; }
        public string PatDescrip { get; set; }
        public int IdUnidad { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public System.DateTime PatFechaAlta { get; set; }
        public System.DateTime PatFechaUnidad { get; set; }
        public Nullable<System.DateTime> PatFechaBaja { get; set; }
        public int IdEstado { get; set; }
        public string IdSecretariaGeneral { get; set; }
        public int IdResponsable { get; set; }
        public int PatCantidad { get; set; }
        public string PatUbicacion { get; set; }
        public string PatFoto { get; set; }
        public Nullable<short> IdInciso { get; set; }
        public Nullable<short> IdPartidaPrincipal { get; set; }
        public Nullable<short> IdPartidaParcial { get; set; }
        public Nullable<short> IdClase { get; set; }
        public Nullable<short> IdItem { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<short> IdOrigen { get; set; }
        public bool Etiqueta { get; set; }
        public Nullable<int> PeriodoAmortiz { get; set; }
        public Nullable<int> InicioAmortiz { get; set; }
        public Nullable<int> IdClasificacion { get; set; }
        public Nullable<int> IdMotivoBaja { get; set; }
        public Nullable<System.DateTime> FechaEtiquetado { get; set; }
        public Nullable<bool> Devengado { get; set; }
        public Nullable<bool> FisicoContable { get; set; }
        public Nullable<int> IdBienUsoGenerico { get; set; }
        public Nullable<bool> Ubicado { get; set; }
        public Nullable<System.DateTime> FechaUbicado { get; set; }
        public Nullable<int> MesInicioAmortiz { get; set; }
        public Nullable<System.DateTime> FechaRelevadoColector { get; set; }
        public string ObservacionesColector { get; set; }
        public Nullable<int> IdUsuarioACargo { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public Nullable<short> Partes { get; set; }
    }
}
